# travis configuration file
# Copyright 2018 Ilya Shipitsin <chipitsine@gmail.com>
#                Nicolas Mora <mail@babelouest.org>
language: c
os: linux
dist: bionic

addons:
  apt:
    packages: [ autoconf, automake, libtool, libsqlite3-dev, libmysqlclient-dev, libpq-dev, libjansson-dev, libsystemd-dev, check, libsubunit-dev, cppcheck ]

jobs:
  include:
    - env: LABEL=gcc
      compiler: gcc
    - env: LABEL=clang
      compiler: clang
    - env: LABEL=cppcheck
      os: linux
      script:
        - cppcheck --force --enable=warning,missingInclude --error-exitcode=1 .

script:
  - mkdir build && cd build
  - cmake -DBUILD_HOEL_TESTING=on ..
  - make
  - sqlite3 /tmp/test.db < ../test/test.sqlite3.sql
  - make test package
  - sudo make install
  - rm -rf * && cmake -DWITH_SQLITE3=off -DWITH_MARIADB=off -DWITH_PGSQL=on ..
  - make package
  - rm -rf * && cmake -DWITH_SQLITE3=off -DWITH_MARIADB=on -DWITH_PGSQL=off ..
  - make package
  - rm -rf * && cmake -DWITH_SQLITE3=off -DWITH_MARIADB=on -DWITH_PGSQL=on ..
  - make package
  - rm -rf * && cmake -DWITH_SQLITE3=on -DWITH_MARIADB=off -DWITH_PGSQL=off ..
  - make package
  - rm -rf * && cmake -DWITH_SQLITE3=on -DWITH_MARIADB=off -DWITH_PGSQL=on ..
  - make package
  - rm -rf * && cmake -DWITH_SQLITE3=on -DWITH_MARIADB=on -DWITH_PGSQL=off ..
  - make package
  - rm -rf * && cmake -DWITH_SQLITE3=on -DWITH_MARIADB=on -DWITH_PGSQL=on ..
  - make package
  - rm -rf *
  - if $(cmake -DWITH_SQLITE3=off -DWITH_MARIADB=off -DWITH_PGSQL=off .. 1>/dev/null 2&>1); then echo "Build with no DB fail" && exit 1; else echo "Build with no DB success"; fi
  - cd ../
  - make clean debug
  - make clean debug DISABLE_SQLITE=1 DISABLE_MARIADB=1
  - make clean debug DISABLE_SQLITE=1 DISABLE_POSTGRESQL=1
  - make clean debug DISABLE_SQLITE=1
  - make clean debug DISABLE_MARIADB=1 DISABLE_POSTGRESQL=1
  - make clean debug DISABLE_MARIADB=1
  - make clean debug DISABLE_POSTGRESQL=1
  - if $(make clean debug DISABLE_SQLITE=1 DISABLE_MARIADB=1 DISABLE_POSTGRESQL=1 1>/dev/null 2&>1); then echo "Build with no DB fail" && exit 1; else echo "Build with no DB success"; fi
  - sqlite3 /tmp/test.db < test/test.sqlite3.sql
  - make clean check
